# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upd_rkn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: curl
      uses: wei/curl@master
      with:
        args: -s -L https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv -o dump.csv
    - name: Process
      run: cat dump.csv | cut -d";" -f1 | tr '|' '\n' | tail -n +2 | sort -u > dump.txt
    - name: Sort Ipv4
      run: grep '\.' dump.txt > ip.lst
    - name: Sort Ipv6
      run: grep ':' dump.txt > ip6.lst
    - name: Commit results
      uses: EndBug/add-and-commit@v9
      with:
        add: '*.lst --force'
